import Link from 'next/link'
import { PageHeader } from '@/components/page-header'
import { getOrganizationOverview } from '@/services/dashboard'

function formatDate(date: string) { return date.split('-').reverse().join('/') }

export default async function HomePage() {
  const overview = await getOrganizationOverview()
  return <><PageHeader title="Home" description={overview.organization.name} /><section className="home-section" aria-labelledby="home-structure"><h2 id="home-structure">Estrutura</h2><div className="metrics"><Link className="metric-link" href="/students"><article><span>Alunos</span><strong>{overview.totalStudents}</strong></article></Link><article><span>Unidades</span><strong>{overview.totalUnits}</strong><small>{overview.mainUnit ? `Principal: ${overview.mainUnit.name}` : 'Nenhuma unidade principal definida.'}</small></article><article><span>Modalidades</span><strong>{overview.totalModalities}</strong></article></div></section><section className="home-section" aria-labelledby="home-operation"><h2 id="home-operation">Operação</h2><div className="metrics"><Link className="metric-link" href="/attendance"><article><span>Presenças hoje</span><strong>{overview.todayAttendanceCount}</strong></article></Link><Link className="metric-link" href="/evolution"><article><span>Avaliações</span><strong>{overview.totalEvaluations}</strong></article></Link><Link className="metric-link" href="/financial"><article><span>Cobranças</span><strong>{overview.totalCharges}</strong></article></Link></div></section><section className="home-activity" aria-labelledby="home-recent-activity"><h2 id="home-recent-activity">Atividade recente</h2><div className="home-activity-grid"><section className="panel" aria-labelledby="recent-attendance"><div className="home-section-heading"><h3 id="recent-attendance">Presenças</h3><Link href="/attendance">Ver presença</Link></div>{overview.recentAttendance.length ? <ul className="home-activity-list">{overview.recentAttendance.map((attendance) => <li key={attendance.id}><strong>{attendance.studentName ?? 'Aluno não disponível'}</strong><span>{formatDate(attendance.date)} · {attendance.unitName ?? 'Unidade não disponível'} · {attendance.modalityName ?? 'Modalidade não disponível'}</span><span>Status: {attendance.status}</span></li>)}</ul> : <p>Nenhuma presença registrada recentemente.</p>}</section><section className="panel" aria-labelledby="recent-evaluations"><div className="home-section-heading"><h3 id="recent-evaluations">Avaliações</h3><Link href="/evolution">Ver evolução</Link></div>{overview.recentEvaluations.length ? <ul className="home-activity-list">{overview.recentEvaluations.map((evaluation) => <li key={evaluation.id}><strong>{evaluation.studentName ?? 'Aluno não disponível'}</strong><span>{formatDate(evaluation.date)} · {evaluation.type} · {evaluation.modalityName ?? 'Modalidade não disponível'}</span></li>)}</ul> : <p>Nenhuma avaliação registrada recentemente.</p>}</section></div></section></>
}
