create schema auth;
create function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;

create role authenticated nologin;
create role anon nologin;

create table public.organizations (id bigint primary key);
create table public.users (
  id uuid primary key,
  organization_id bigint not null references public.organizations(id),
  status text not null
);
create table public.students (
  id bigint primary key,
  organization_id bigint not null references public.organizations(id)
);
create table public.units (
  id bigint primary key,
  organization_id bigint not null references public.organizations(id),
  status text not null
);
create table public.plans (
  id bigint primary key,
  organization_id bigint not null references public.organizations(id)
);
create table public.student_plans (
  id bigint primary key,
  student_id bigint not null references public.students(id),
  unit_id bigint not null references public.units(id),
  plan_id bigint not null references public.plans(id),
  status text not null default 'active',
  end_date date
);
create table public.charges (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id),
  student_id bigint not null references public.students(id),
  unit_id bigint not null references public.units(id),
  student_plan_id bigint not null references public.student_plans(id),
  issue_date date not null,
  due_date date not null,
  value numeric(12,2) not null,
  status text not null check (status in ('pending', 'overdue', 'paid', 'cancelled')),
  description text,
  observation text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.payments (
  id bigint generated by default as identity primary key,
  charge_id bigint not null references public.charges(id),
  amount_paid numeric(12,2) not null,
  payment_date date not null,
  payment_method text not null check (payment_method in ('cash', 'pix', 'card', 'transfer')),
  observation text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.charges enable row level security;
alter table public.payments enable row level security;
create policy charges_select_org on public.charges for select to authenticated using (
  organization_id = (select organization_id from public.users where id = auth.uid() and status = 'active')
);
create policy charges_insert_org on public.charges for insert to authenticated with check (
  organization_id = (select organization_id from public.users where id = auth.uid() and status = 'active')
);
create policy charges_update_org on public.charges for update to authenticated using (
  organization_id = (select organization_id from public.users where id = auth.uid() and status = 'active')
) with check (
  organization_id = (select organization_id from public.users where id = auth.uid() and status = 'active')
);
create policy charges_delete_org on public.charges for delete to authenticated using (
  organization_id = (select organization_id from public.users where id = auth.uid() and status = 'active')
);
create policy payments_select_org on public.payments for select to authenticated using (
  exists (select 1 from public.charges c where c.id = payments.charge_id and c.organization_id = (select organization_id from public.users where id = auth.uid() and status = 'active'))
);
create policy payments_insert_org on public.payments for insert to authenticated with check (
  exists (select 1 from public.charges c where c.id = payments.charge_id and c.organization_id = (select organization_id from public.users where id = auth.uid() and status = 'active'))
);
grant usage on schema public, auth to authenticated;
grant select, insert, update, delete on public.charges, public.payments to authenticated;

insert into public.organizations values (15), (16);
insert into public.users values
  ('00000000-0000-0000-0000-000000000015', 15, 'active'),
  ('00000000-0000-0000-0000-000000000016', 16, 'active');
insert into public.students values (15, 15), (16, 16);
insert into public.units values (13, 15, 'active'), (16, 16, 'active');
insert into public.plans values (10, 15), (16, 16);
insert into public.student_plans (id, student_id, unit_id, plan_id, status) values
  (12, 15, 13, 10, 'active'), (16, 16, 16, 16, 'active');
insert into public.charges (id, organization_id, student_id, unit_id, student_plan_id, issue_date, due_date, value, status)
values (9, 15, 15, 13, 12, '2026-10-01', '2026-10-10', 100.00, 'pending');
insert into public.payments (id, charge_id, amount_paid, payment_date, payment_method, observation)
values (11, 9, 100.00, '2026-10-07', 'pix', 'Pagamento de homologação do SLT.');
