-- Disposable LOCAL test fixture only. Never apply to Supabase.
create schema private;
create schema auth;
do $$ begin
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then create role authenticated; end if;
  if not exists (select 1 from pg_roles where rolname = 'anon') then create role anon; end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then create role service_role; end if;
end $$;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
create table public.organizations(id bigint primary key);
create table public.users(id uuid primary key, organization_id bigint references public.organizations, status text not null);
create table public.units(id bigint primary key, organization_id bigint not null references public.organizations, status text not null);
create table public.modalities(
  id bigint generated by default as identity primary key,
  unit_id bigint not null references public.units on delete restrict,
  name text not null, description text,
  status text not null default 'active' check(status in ('active','inactive')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index modalities_unit_id_idx on public.modalities(unit_id);
create table public.student_modality_units(id bigint primary key, student_id bigint, unit_id bigint, modality_id bigint not null references public.modalities on delete restrict, status text default 'active');
create unique index student_modality_units_active_uidx on public.student_modality_units(student_id,modality_id,unit_id) where status='active';
create table public.attendance(id bigint primary key, modality_id bigint not null references public.modalities on delete restrict);
create table public.evaluations(id bigint primary key, modality_id bigint not null references public.modalities on delete restrict);
create table public.trainings(id bigint primary key, student_modality_unit_id bigint not null references public.student_modality_units on delete restrict);
create table public.training_exercises(id bigint primary key, training_id bigint not null references public.trainings on delete cascade);
create table public.evaluation_results(id bigint primary key, evaluation_id bigint not null references public.evaluations on delete cascade);
create function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
create trigger modalities_set_updated_at before update on public.modalities for each row execute function public.set_updated_at();
create function private.current_user_organization_id() returns bigint language sql stable security definer set search_path = public as $$ select organization_id from public.users where id=auth.uid() and status='active' limit 1 $$;
revoke all on function private.current_user_organization_id() from public;
grant usage on schema public, private, auth to authenticated;
grant execute on function private.current_user_organization_id() to authenticated;
alter table public.units enable row level security;
alter table public.modalities enable row level security;
create policy units_select_org on public.units for select to authenticated using(organization_id=(select private.current_user_organization_id()));
create policy modalities_select_org on public.modalities for select to authenticated using(exists(select 1 from public.units u where u.id=modalities.unit_id and u.organization_id=(select private.current_user_organization_id())));
create policy modalities_insert_org on public.modalities for insert to authenticated with check(exists(select 1 from public.units u where u.id=modalities.unit_id and u.organization_id=(select private.current_user_organization_id())));
create policy modalities_update_org on public.modalities for update to authenticated using(exists(select 1 from public.units u where u.id=modalities.unit_id and u.organization_id=(select private.current_user_organization_id()))) with check(exists(select 1 from public.units u where u.id=modalities.unit_id and u.organization_id=(select private.current_user_organization_id())));
create policy modalities_delete_org on public.modalities for delete to authenticated using(exists(select 1 from public.units u where u.id=modalities.unit_id and u.organization_id=(select private.current_user_organization_id())));
grant select on public.units to authenticated;
grant select,insert,update,delete on public.modalities to authenticated;
grant usage,select on all sequences in schema public to authenticated;
insert into public.organizations values(15),(16);
insert into public.users values('00000000-0000-0000-0000-000000000015',15,'active'),('00000000-0000-0000-0000-000000000016',16,'active');
insert into public.units values(13,15,'active'),(14,15,'active'),(16,16,'active');
insert into public.modalities(id,unit_id,name,description,status,created_at,updated_at) values
 (11,13,'Natação','Natação','inactive','2026-10-05 18:34:03.343181+00','2026-10-05 18:34:31.010877+00'),
 (12,13,'Natação','Natação','active','2026-10-05 18:34:07.695546+00','2026-10-05 18:34:07.695546+00'),
 (13,13,'futebol','Futebol','active','2026-10-06 12:00:00+00','2026-10-06 12:00:00+00');
select setval(pg_get_serial_sequence('public.modalities','id'),100);
