import { createClient } from '@/lib/supabase/server'
import type { Tables } from '@/types/supabase'
import { studentModalityUnitSchema, type StudentModalityUnitInput } from '@/validations/student-modality-unit'
import { getActiveModality } from './modalities'
import { getActiveUnit, listActiveUnits } from './units'
export type StudentModalityUnit = Tables<'student_modality_units'>
export async function listStudentModalityUnits(studentId: number): Promise<StudentModalityUnit[]> { const supabase = await createClient(); const { data, error } = await supabase.from('student_modality_units').select('*').eq('student_id', studentId).order('start_date', { ascending: false }); if (error) throw new Error('Não foi possível carregar os vínculos esportivos.'); return data }
export async function listActiveStudentModalityUnits(studentId: number): Promise<StudentModalityUnit[]> { const [links, units] = await Promise.all([listStudentModalityUnits(studentId), listActiveUnits()]); const activeUnitIds = new Set(units.map((unit) => unit.id)); return (await Promise.all(links.map(async (link) => { if (!activeUnitIds.has(link.unit_id)) return null; try { const modality = await getActiveModality(link.modality_id); return modality.unit_id === link.unit_id ? link : null } catch { return null } }))).filter((link): link is StudentModalityUnit => link !== null) }
export async function createStudentModalityUnit(studentId: number, input: StudentModalityUnitInput): Promise<StudentModalityUnit> { const payload = studentModalityUnitSchema.parse(input); await getActiveUnit(payload.unit_id); const modality = await getActiveModality(payload.modality_id); if (modality.unit_id !== payload.unit_id) throw new Error('A modalidade não pertence à unidade selecionada.'); const supabase = await createClient(); const { data, error } = await supabase.from('student_modality_units').insert({ ...payload, student_id: studentId }).select().single(); if (error) throw new Error('Não foi possível criar o vínculo esportivo.'); return data }
