import { createClient } from '@/lib/supabase/server'; import { trainingSchema, trainingExerciseSchema } from '@/validations/training-plan'; import type { Tables } from '@/types/supabase'
export type Training = Tables<'trainings'>; export type TrainingExercise = Tables<'training_exercises'>
export async function listTrainingsByStudent(studentId:number) { const s=await createClient(); const {data,error}=await s.from('trainings').select('*, student_modality_units!inner(student_id)').eq('student_modality_units.student_id',studentId).order('created_at',{ascending:false}); if(error) throw new Error('Não foi possível carregar os treinamentos.'); return data }
export async function createTraining(studentId:number,input:unknown) { const p=trainingSchema.parse(input); const s=await createClient(); const {data:ctx,error:ctxError}=await s.from('student_modality_units').select('id').eq('id',p.student_modality_unit_id).eq('student_id',studentId).single(); if(ctxError||!ctx) throw new Error('Contexto esportivo inválido.'); const {data,error}=await s.from('trainings').insert(p).select().single(); if(error) throw new Error('Não foi possível criar o treinamento.'); return data }
export async function listTrainingExercises(trainingId:number) { const s=await createClient(); const {data,error}=await s.from('training_exercises').select('*').eq('training_id',trainingId).order('order'); if(error) throw new Error('Não foi possível carregar exercícios.'); return data }
export async function createTrainingExercise(trainingId:number,input:unknown) { const s=await createClient(); const p=trainingExerciseSchema.parse(input); const {data,error}=await s.from('training_exercises').insert({...p,training_id:trainingId}).select().single(); if(error) throw new Error('Não foi possível criar exercício.'); return data }
export async function updateTraining(id:number,input:unknown) { const s=await createClient(); const { student_modality_unit_id, ...p }=trainingSchema.partial().parse(input); if(student_modality_unit_id!==undefined) throw new Error('O contexto esportivo do treinamento não pode ser alterado.'); const {data,error}=await s.from('trainings').update(p).eq('id',id).select().single(); if(error) throw new Error('Não foi possível atualizar o treinamento.'); return data }
export async function updateTrainingStatus(id:number,status:string) { return updateTraining(id,{status}) }
export async function updateTrainingExercise(id:number,input:unknown) { const s=await createClient(); const p=trainingExerciseSchema.partial().parse(input); const {data,error}=await s.from('training_exercises').update(p).eq('id',id).select().single(); if(error) throw new Error('Não foi possível atualizar exercício.'); return data }
export async function deleteTrainingExercise(id:number) { const s=await createClient(); const {error}=await s.from('training_exercises').delete().eq('id',id); if(error) throw new Error('Não foi possível remover exercício.') }
export async function reorderTrainingExercises(trainingId:number,exerciseIds:number[]) { const s=await createClient(); for (const [order,id] of exerciseIds.entries()) { const {error}=await s.from('training_exercises').update({order}).eq('id',id).eq('training_id',trainingId); if(error) throw new Error('Não foi possível reorganizar exercícios.') } }
