import Link from 'next/link'
import { notFound } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { getEvaluation, listEvaluationResults } from '@/services/evaluations'
import { listModalities } from '@/services/modalities'
import { listStudents } from '@/services/students'
import { listUnits } from '@/services/units'
import { addEvaluationResultAction, removeEvaluationResultAction, updateEvaluationAction, updateEvaluationResultAction } from '../actions'

export default async function EvaluationPage({params}:{params:Promise<{id:string}>}){const id=Number((await params).id);let evaluation;try{evaluation=await getEvaluation(id)}catch{notFound()}const [results,students,units,modalities]=await Promise.all([listEvaluationResults(id),listStudents(),listUnits(),listModalities()]);const s=await createClient();const {data:user}=await s.from('users').select('name').eq('id',evaluation.responsible_user_id).single();const student=students.find(x=>x.id===evaluation.student_id);const unit=units.find(x=>x.id===evaluation.unit_id);const modality=modalities.find(x=>x.id===evaluation.modality_id);return <><Link href="/evolution">← Evolução</Link><h1>{evaluation.type}</h1><section className="panel"><p>{student?.full_name||`Aluno #${evaluation.student_id}`} · {unit?.name||`Unidade #${evaluation.unit_id}`} · {modality?.name||`Modalidade #${evaluation.modality_id}`}</p><p>{new Date(`${evaluation.date}T00:00:00`).toLocaleDateString('pt-BR')} · Responsável: {user?.name||'Não informado'}</p><form action={updateEvaluationAction.bind(null,id)} className="student-form"><label>Data<input name="date" type="date" defaultValue={evaluation.date}/></label><label>Tipo<input name="type" defaultValue={evaluation.type}/></label><button>Salvar avaliação</button></form></section><section className="panel"><h2>Resultados</h2>{results.length?<ul>{results.map(r=><li key={r.id}><details><summary>{r.metric}: {r.value} {r.unit_of_measure||''}</summary><form action={updateEvaluationResultAction.bind(null,id,r.id)} className="student-form"><label>Métrica<input name="metric" defaultValue={r.metric}/></label><label>Valor<input name="value" defaultValue={r.value}/></label><label>Unidade<input name="unit_of_measure" defaultValue={r.unit_of_measure||''}/></label><label>Observação<textarea name="observation" defaultValue={r.observation||''}/></label><button>Salvar resultado</button></form></details><form action={removeEvaluationResultAction.bind(null,id)}><input type="hidden" name="result_id" value={r.id}/><button>Remover</button></form></li>)}</ul>:<p>Nenhum resultado registrado.</p>}<form action={addEvaluationResultAction.bind(null,id)} className="student-form"><h2>Adicionar resultado</h2><label>Métrica<input name="metric" required/></label><label>Valor<input name="value" required/></label><label>Unidade de medida<input name="unit_of_measure"/></label><label>Observação<textarea name="observation"/></label><button>Adicionar resultado</button></form></section></>}
