import { ModalityCreateForm } from '@/components/modalities/modality-create-form'
import { ModalityCreateSubmitButton } from '@/components/modalities/modality-create-submit-button'
import { modalityDuplicateMessages } from '@/domain/modality-name'
import Link from 'next/link'
import { listModalities } from '@/services/modalities'
import { listActiveUnits, listUnits } from '@/services/units'
import { saveModality } from '../actions'

export default async function ModalitiesPage({ searchParams }: { searchParams: Promise<{ created?: string; error?: string }> }) {
  const [modalities, units, activeUnits, params] = await Promise.all([listModalities(), listUnits(), listActiveUnits(), searchParams])
  const unitsById = new Map(units.map((unit) => [unit.id, unit.name]))

  return <><Link href="/settings">← Configurações</Link><h1>Modalidades</h1><section className="panel">{modalities.length ? <div className="student-list">{modalities.map((modality) => <Link className="student-row" href={`/settings/modalities/${modality.id}`} key={modality.id}><div><strong>{modality.name}</strong><span>{unitsById.get(modality.unit_id) ?? 'Unidade não disponível'}{modality.description ? ` · ${modality.description}` : ''}</span></div><span className="status-badge">{modality.status === 'active' ? 'Ativa' : 'Inativa'}</span></Link>)}</div> : <div className="empty-state"><h2>Nenhuma modalidade cadastrada</h2><p>Crie a primeira modalidade de uma unidade.</p></div>}</section>{params.created && <p className="form-success" role="status">Modalidade criada com sucesso.</p>}{params.error === 'validation' && <p className="form-error" role="alert">Revise os campos informados e tente novamente.</p>}{params.error === 'unit' && <p className="form-error" role="alert">A unidade selecionada não está ativa ou não está disponível para sua organização.</p>}{params.error === 'update' && <p className="form-error" role="alert">Não foi possível salvar a modalidade. Tente novamente.</p>}{params.error === 'duplicate-active' && <p className="form-error" role="alert">{modalityDuplicateMessages.active}</p>}{params.error === 'duplicate-inactive' && <p className="form-error" role="alert">{modalityDuplicateMessages.inactive}</p>}<ModalityCreateForm action={saveModality.bind(null, undefined)}><section className="form-section"><h2>Nova modalidade</h2><div className="form-grid"><label>Nome *<input name="name" required /></label><label>Unidade *<select name="unit_id" required><option value="">Selecione</option>{activeUnits.map((unit) => <option value={unit.id} key={unit.id}>{unit.name}</option>)}</select></label><label className="span-2">Descrição<textarea name="description" /></label></div><p className="muted-note">Novas modalidades só podem ser criadas em unidades ativas.</p></section><div className="form-actions"><ModalityCreateSubmitButton /></div></ModalityCreateForm></>
}
