import Link from 'next/link'
import { PageHeader } from '@/components/page-header'
import { OperationalForm, OperationalSubmitButton } from '@/components/operational-form'
import { listPlans } from '@/services/plans'
import { planStatusAction, savePlanAction } from '../actions'

export default async function PlansPage() {
  const plans = await listPlans()
  return <><PageHeader title="Planos" description="Gerencie os planos da organização." action={<Link className="button" href="/financial">← Financeiro</Link>} /><section className="panel">{plans.length ? <div className="student-list">{plans.map((plan) => <article className="student-row" key={plan.id}><div><strong>{plan.name}</strong><span>{plan.periodicity} · R$ {plan.value.toFixed(2)} · {plan.status}</span></div><details><summary>Editar plano</summary><OperationalForm action={savePlanAction.bind(null, plan.id)} className="student-form" successMessage="Plano atualizado com sucesso."><label>Nome *<input name="name" required defaultValue={plan.name} /></label><label>Descrição<textarea name="description" defaultValue={plan.description || ''} /></label><label>Periodicidade *<input name="periodicity" required defaultValue={plan.periodicity} /></label><label>Valor *<input name="value" type="number" step="0.01" min="0.01" required defaultValue={plan.value} /></label><label>Status<input name="status" defaultValue={plan.status} /></label><OperationalSubmitButton idleLabel="Salvar alterações" pendingLabel="Salvando..." /></OperationalForm></details><OperationalForm action={planStatusAction.bind(null, plan.id)} successMessage="Status do plano atualizado com sucesso."><input name="status" defaultValue={plan.status} /><OperationalSubmitButton idleLabel="Atualizar status" pendingLabel="Atualizando..." /></OperationalForm></article>)}</div> : <div className="empty-state"><h2>Nenhum plano cadastrado</h2><p>Crie o primeiro plano para vincular aos alunos.</p></div>}</section><OperationalForm action={savePlanAction.bind(null, undefined)} className="student-form" successMessage="Plano criado com sucesso."><section className="form-section"><h2>Novo plano</h2><div className="form-grid"><label>Nome *<input name="name" required /></label><label>Periodicidade *<input name="periodicity" required /></label><label>Valor *<input name="value" type="number" step="0.01" min="0.01" required /></label><label>Status<input name="status" /></label><label className="span-2">Descrição<textarea name="description" /></label></div></section><div className="form-actions"><OperationalSubmitButton idleLabel="Criar plano" pendingLabel="Criando..." /></div></OperationalForm></>
}
