'use server'
import { revalidatePath } from 'next/cache'; import { redirect } from 'next/navigation'; import { updateCurrentOrganization } from '@/services/organizations'; import { createUnit, setUnitAsMain, updateUnit } from '@/services/units'; import { createModality, updateModality } from '@/services/modalities'; import { organizationUpdateSchema, type OrganizationUpdateInput, type UnitInput, unitSchema, modalitySchema } from '@/validations/settings'
const values = (f: FormData) => Object.fromEntries([...f].map(([k,v]) => [k, v === '' ? undefined : v]))
const organizationValues = (f: FormData) => Object.fromEntries([...f].map(([k, v]) => [k, v === '' ? null : v]))
const unitValues = (f: FormData) => Object.fromEntries(['name', 'code', 'email', 'phone', 'cep', 'state', 'city', 'neighborhood', 'street', 'number', 'complement'].map((key) => [key, f.get(key) === '' ? null : f.get(key)]))
export async function saveOrganization(f: FormData) { let input: OrganizationUpdateInput; try { input = organizationUpdateSchema.parse(organizationValues(f)) } catch { redirect('/settings/organization?error=validation') } try { await updateCurrentOrganization(input) } catch { redirect('/settings/organization?error=update') } revalidatePath('/settings/organization'); redirect('/settings/organization?updated=1') }
export async function saveUnit(id: number | undefined, f: FormData) { let input: UnitInput; try { input = unitSchema.parse(unitValues(f)) } catch { redirect(id ? `/settings/units/${id}?error=validation` : '/settings/units?error=validation') } try { if (id) await updateUnit(id, input); else await createUnit(input) } catch { redirect(id ? `/settings/units/${id}?error=update` : '/settings/units?error=update') } revalidatePath('/settings/units'); if (id) { revalidatePath(`/settings/units/${id}`); redirect(`/settings/units/${id}?updated=1`) } redirect('/settings/units?created=1') }
export async function makeUnitMain(id: number) { try { await setUnitAsMain(id) } catch { redirect(`/settings/units/${id}?error=main`) } revalidatePath('/settings/units'); revalidatePath(`/settings/units/${id}`); redirect(`/settings/units/${id}?main=1`) }
export async function saveModality(f: FormData) { const input = modalitySchema.parse(values(f)); const id = Number(f.get('id')); if (id) await updateModality(id, input); else await createModality(input); revalidatePath('/settings/modalities') }
