'use server'
import{revalidatePath}from 'next/cache';import{cancelCharge,createCharge,financialChargeMessage}from '@/services/charges';import{createPlan,updatePlan,updatePlanStatus}from '@/services/plans';import{createStudentPlan,endStudentPlan}from '@/services/student-plans';import{createPayment}from '@/services/payments';import{operationFailure,operationSuccess,type OperationalActionResult}from '@/lib/operational-result';import{planSchema}from '@/validations/plan';import{studentPlanSchema}from '@/validations/student-plan';import{chargeSchema}from '@/validations/charge';import{paymentSchema}from '@/validations/payment'
const data=(f:FormData)=>Object.fromEntries([...f].map(([k,v])=>[k,v===''?undefined:v]))
export async function savePlanAction(id:number|undefined,f:FormData){const p=planSchema.parse(data(f));if(id)await updatePlan(id,p);else await createPlan(p);revalidatePath('/financial')}
export async function planStatusAction(id:number,f:FormData){await updatePlanStatus(id,String(f.get('status')));revalidatePath('/financial')}
export async function createStudentPlanAction(f:FormData){await createStudentPlan(studentPlanSchema.parse(data(f)));revalidatePath('/financial')}
export async function endStudentPlanAction(id:number,f:FormData){await endStudentPlan(id,String(f.get('end_date')),String(f.get('status')));revalidatePath('/financial')}
export async function createChargeAction(f:FormData):Promise<OperationalActionResult>{try{await createCharge(chargeSchema.parse(data(f)));revalidatePath('/financial');revalidatePath('/financial/charges');return operationSuccess('Cobrança criada com sucesso.')}catch(error){return operationFailure(financialChargeMessage(error))}}
export async function createPaymentAction(f:FormData):Promise<OperationalActionResult>{try{await createPayment(paymentSchema.parse(data(f)));const chargeId=Number(f.get('charge_id'));revalidatePath('/financial');revalidatePath(`/financial/charges/${chargeId}`);return operationSuccess('Pagamento registrado com sucesso.')}catch(error){return operationFailure(error instanceof Error?error.message:'Não foi possível registrar o pagamento.')}}
export async function cancelChargeAction(id:number):Promise<OperationalActionResult>{try{await cancelCharge(id);revalidatePath('/financial');revalidatePath(`/financial/charges/${id}`);return operationSuccess('Cobrança cancelada com sucesso.')}catch(error){return operationFailure(financialChargeMessage(error))}}
