'use client'
import { useActionState } from 'react'
import type { Student } from '@/services/students'
import type { StudentFormState } from '@/app/(protected)/students/actions'
type StudentFormProps = { student?: Student; action: (state: StudentFormState, formData: FormData) => Promise<StudentFormState> }
const initialState: StudentFormState = { status: 'idle' }
function fieldError(state: StudentFormState, field: string) { return state.fieldErrors?.[field]?.[0] }
export function StudentForm({ student, action }: Readonly<StudentFormProps>) {
  const [state, formAction, pending] = useActionState(action, initialState)
  const value = (field: keyof Student) => student?.[field] ?? ''
  return <form action={formAction} className="student-form">{state.status === 'error' && state.message && <p className="form-error" role="alert">{state.message}</p>}<section className="form-section"><h2>Dados pessoais</h2><div className="form-grid"><label className="span-2">Nome completo *<input name="full_name" required defaultValue={value('full_name')} />{fieldError(state, 'full_name') && <small>{fieldError(state, 'full_name')}</small>}</label><label>Data de nascimento *<input name="birth_date" type="date" required defaultValue={value('birth_date')} />{fieldError(state, 'birth_date') && <small>{fieldError(state, 'birth_date')}</small>}</label><label>Nome social<input name="social_name" defaultValue={value('social_name')} /></label><label>CPF<input name="cpf" inputMode="numeric" defaultValue={value('cpf')} /></label><label>Status<input name="status" defaultValue={value('status')} placeholder="Usar padrão do sistema" /></label><label>Sexo<input name="sex" defaultValue={value('sex')} /></label><label className="span-2">Foto (URL)<input name="photo" type="url" defaultValue={value('photo')} /></label></div></section><section className="form-section"><h2>Contato</h2><div className="form-grid"><label className="span-2">E-mail<input name="email" type="email" defaultValue={value('email')} /></label><label>Telefone<input name="phone" type="tel" defaultValue={value('phone')} /></label><label>WhatsApp<input name="whatsapp" type="tel" defaultValue={value('whatsapp')} /></label></div></section><details className="form-section"><summary>Endereço e informações esportivas</summary><div className="form-grid details-grid"><label>CEP<input name="cep" defaultValue={value('cep')} /></label><label>Estado<input name="state" defaultValue={value('state')} /></label><label>Rua<input name="street" defaultValue={value('street')} /></label><label>Número<input name="number" defaultValue={value('number')} /></label><label>Complemento<input name="complement" defaultValue={value('complement')} /></label><label>Bairro<input name="neighborhood" defaultValue={value('neighborhood')} /></label><label>Município<input name="city" defaultValue={value('city')} /></label><label>Início na organização<input name="start_date" type="date" defaultValue={value('start_date')} /></label><label className="span-2">Observações esportivas<textarea name="sports_notes" defaultValue={value('sports_notes')} /></label></div></details><div className="form-actions"><button type="submit" disabled={pending}>{pending ? 'Salvando...' : student ? 'Salvar alterações' : 'Cadastrar aluno'}</button></div></form>
}
