import Link from 'next/link'
import { notFound } from 'next/navigation'
import { getUnit } from '@/services/units'
import { makeUnitMain, saveUnit } from '../../actions'

export default async function UnitPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ updated?: string; main?: string; error?: string }> }) {
  const id = Number((await params).id)
  if (!Number.isInteger(id) || id < 1) notFound()
  let unit
  try { unit = await getUnit(id) } catch { notFound() }
  const query = await searchParams
  return <><Link href="/settings/units">← Unidades</Link><h1>{unit.name}</h1><form action={saveUnit.bind(null, unit.id)} className="student-form"><section className="form-section"><h2>Dados da unidade</h2><div className="form-grid"><label>Nome *<input name="name" required defaultValue={unit.name} /></label><label>Código<input name="code" defaultValue={unit.code ?? ''} /></label><label>E-mail<input name="email" type="email" defaultValue={unit.email ?? ''} /></label><label>Telefone<input name="phone" type="tel" defaultValue={unit.phone ?? ''} /></label></div>{unit.logo && <p className="muted-note">Logo cadastrada. A edição de logo não está disponível nesta versão.</p>}</section><section className="form-section"><h2>Endereço</h2><div className="form-grid"><label>CEP<input name="cep" defaultValue={unit.cep ?? ''} /></label><label>Estado<input name="state" defaultValue={unit.state ?? ''} /></label><label>Cidade<input name="city" defaultValue={unit.city ?? ''} /></label><label>Bairro<input name="neighborhood" defaultValue={unit.neighborhood ?? ''} /></label><label>Rua<input name="street" defaultValue={unit.street ?? ''} /></label><label>Número<input name="number" defaultValue={unit.number ?? ''} /></label><label className="span-2">Complemento<input name="complement" defaultValue={unit.complement ?? ''} /></label></div></section><section className="form-section"><h2>Situação</h2><p>Status atual: <strong>{unit.status}</strong></p><p>{unit.is_main ? 'Esta é a unidade principal da organização.' : 'Esta não é a unidade principal da organização.'}</p><p className="muted-note">A alteração de status não está disponível enquanto os valores canônicos não estiverem formalmente definidos.</p></section>{query.updated && <p className="form-success" role="status">Unidade atualizada com sucesso.</p>}{query.main && <p className="form-success" role="status">Unidade definida como principal.</p>}{query.error === 'validation' && <p className="form-error" role="alert">Revise os campos informados e tente novamente.</p>}{query.error === 'update' && <p className="form-error" role="alert">Não foi possível atualizar a unidade. Tente novamente.</p>}{query.error === 'main' && <p className="form-error" role="alert">Não foi possível definir a unidade principal. Tente novamente.</p>}<div className="form-actions"><button>Salvar alterações</button></div></form>{!unit.is_main && <form action={makeUnitMain.bind(null, unit.id)}><button>Definir como unidade principal</button></form>}</>
}
